### ISSUE TITLE
Suggestion for External Links script

### ISSUE THREAD

**Issue by parfait8566** [stephenmk/edrdg-scripts#3]
First of all, there seems to be a weird bug (tested on both Firefox-based and Chromium-based browsers, on Violentmonkey) where if you install the External Links script before the Collapsible Updates script the "External Links" button won't actually open in the updates page. Might be useful to add some sort of "install after Collapsible Updates script" note.

Secondly I suggest adding WWWJDIC to the External Links script.
WWWJDIC seems to use EUC URL encoding so what I did with the help of ChatGPT was adding
`// @require     https://cdn.jsdelivr.net/npm/encoding-japanese/encoding.min.js`
to the beginning of the script,
`  "wwwjdic":    "http://nihongo.monash.edu/cgi-bin/wwwjdic?1MDE$1"`
to `const urls`,
```
function encodeToEUCJP(text) {
    const eucJPArray = Encoding.convert(text, { to: 'EUCJP' });
    return Encoding.urlEncode(eucJPArray);
}
```
as a function,
```
      const eucExpression = encodeToEUCJP(expression);
      menuItems.push(makeLink("WWWJDIC", `${urls["wwwjdic"]}`.replace("$1", eucExpression), []));
```
to `menuItems`.

I haven't tested extensively and I'm not sure at all if this is the most efficient way to do it, but it seems to be working on my end.

**Comment by stephenmk** [comment]
That's a good idea.

You can change the parameters in the URL query string to be able to pass utf-8 strings. The documentation is here: https://www.edrdg.org/wwwjdic/wwwjdicinf.html#backdoor_tag

**Comment by stephenmk** [comment]
I updated the script to resolve the installation order issue and also add the wwwjdic link.
